name: Test GPG private key import
on: workflow_dispatch


jobs:
  publish:
    name: Publish package
    # run only when pull request was merged
#    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase

      - name: Check settings
        run: cat /home/runner/.m2/settings.xml
        
      - name: Check GPG
        run: gpg --help
        
      - name: List Secrets
        run: gpg --list-secret-keys --keyid-format LONG