name: Test GPG private key import
on: workflow_dispatch

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Get App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env: 
          TOKEN: ${{ steps.get_token.outputs.app_token }}
      
      - uses: actions/checkout@v3
      
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase

      - name: Check settings
        run: cat /home/runner/.m2/settings.xml
        
      - name: Check GPG
        run: gpg --help
        
      - name: List Secrets
        run: gpg --list-secret-keys --keyid-format LONG
